// vue-chat/src/components/ChatWindow.vue
<script setup lang="ts">
import ConnectionStatus from "./ConnectionStatus.vue";
import MessageList from "./MessageList.vue";
import MessageInput from "./MessageInput.vue";
</script>

<template>
  <div>
    <h2>Chat Realtime</h2>

    <ConnectionStatus />

    <MessageList />

    <MessageInput />
  </div>
</template>

// react-chat/src/components/ChatWindow.tsx
import ConnectionStatus from "./ConnectionStatus";
import MessageList from "./MessageList";
import MessageInput from "./MessageInput";

export default function ChatWindow() {
  return (
    <div>
      <h2>Chat Realtime</h2>

      <ConnectionStatus />

      <MessageList />

      <MessageInput />
    </div>
  );
}
